---
- name: Install Nginx and start it
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure Nginx is at the latest version
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Ensure Nginx is started and enabled on boot
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
